language: C
git:
  depth: 9999999
os:
- linux
compiler:
- clang
matrix:
  include:
  - os: osx
    compiler: clang
    env: VERS=macos DEPLOY=yes
  - os: linux
    compiler: gcc
    env: VERS=win DEPLOY=yes
  - os: linux
    compiler: gcc
    env: VERS=linux DEPLOY=yes
dist: trusty
sudo: required
branches:
  only: master
install: |-
  if [ "$VERS" == "win" ] # Cross compiling for Windows
  then
    sudo add-apt-repository "deb http://fr.archive.ubuntu.com/ubuntu/ xenial main restricted universe multiverse" # We need an up-to-date MinGW
    sudo apt-get update
    sudo apt-get -qy install libsdl2-dev rpm libegl1-mesa-dev libgles2-mesa-dev libxi-dev libxrandr-dev freeglut3
    sudo apt-get install -t xenial gcc-mingw-w64-i686 g++-mingw-w64-i686 mingw32-runtime
  elif [ "$VERS" == "linux" ]
  then
    sudo apt-get -qy install libsdl2-dev rpm libegl1-mesa-dev libgles2-mesa-dev libxi-dev libxrandr-dev freeglut3  # freeglut probably pulls libxi-dev in
  elif [ "$VERS" == "macos" ]
  then
    echo "Building macOS"
    brew install sdl2
  fi
script: |-
  if [ "$VERS" == "win" ]
  then
    ./makecrosswin.sh || exit 1
  elif [ "$VERS" == "linux" ]
  then
    if [ "$CXX" == "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
    ./makelinux.sh || exit 1
  elif [ "$VERS" == "macos" ]
  then
    if [ "$CXX" == "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
    ./makemacos.sh || exit 1
  fi
before_deploy: |-
  if [ "$VERS" == "macos" ]
  then
    export DEPLOY_BIN=fbvpdf-macos.zip
    export DEPLOY_PKG=fbvpdf.dmg
  elif [ "$VERS" == "win" ]
  then
    export DEPLOY_BIN=build/release/mupdf-win.exe
    export DEPLOY_PKG=fbvpdf.zip
  elif [ "$VERS" == "linux" ]
  then
    export DEPLOY_BIN=build/release/mupdf-linux
    export DEPLOY_PKG=fbvpdf.tar.gz
  fi
deploy:
  provider: releases
  api_key:
    secure: VC6ik6R8PaL36CKbeAjlS1kYz2K8zaoqItUtrhLifyP0dPzM7Lfxelyzunl6s5pUTQMlMS4KDLYCcp6sIwVpHmUBjYXYLfr+mDPiTywZKOocdhzDIlF8gCUCegHk9/6Ytz6yTSHzuT+gpBph/gvUU39aDEHAyuzfac08hwe7HqXMu5ErZN2rAwIo5vrQ1YT2ai4FMi3gZOiDacoFF5iF6ZVLWUpa1MsvC2GFZeOPt9B3gQwDxPy10yc4Om7JoxoUsMU099/2j6wJyumGG2zms9tGwPv3H5zJ4Py8psqE1EPpRh56IjGdgGY4oiTix+5tzBAVZDdv39DmRKdh2o/uVAsaRzdueGMIuqSz8GvWfNQm9vI8ett6Yf6QCdGkVeaqH+FH28b2Qp74B+OSE+jKMklrTphEv7nEflUJmbu9hpDxWqHmPXhLQ7nKIEg+qws+HD41lqpESA6wPEOA06yUoOBgCT0U97noONWKXrr0LZyMN207UmxXczuL0tufXZaiUwzhNO5trZYofEFfO08npZ7vjbr8u8vVT5PnQ+WItJ4nAqqtVKrpLxFhNxRY5nZwX3Z8kaJsql07VBgLuCTqE9hP97gIjE6vhnOyuWKYjzFHN6915Jk09+l9gj3WPmGYGQaHpUd6PT8NyoEbiiiqLwfVScbpvNv61b26hfUCf1M=
  file:
    - "${DEPLOY_BIN}"
    - "${DEPLOY_PKG}"
  skip_cleanup: true
  on:
    repo: pvtinflex/fbvpdf
