language: C
git:
  depth: 9999999
os:
- linux
compiler:
- clang
matrix:
  include:
  - os: linux
    compiler: gcc
    env: DEPLOY=yes OS_TYPE=linux
  - os: osx
    compiler: clang
    env: DEPLOY=yes OS_TYPE=macos
  - os: linux
    compiler: gcc
    env: CROSS=mingw64 DEPLOY=yes
dist: trusty
sudo: required
branches:
  only: master
install: |-
  if [ "$TRAVIS_OS_NAME" == "linux" ]
  then
    if [ "$CROSS" == "mingw64" ] # Cross compiling for Windows
    then
      sudo add-apt-repository "deb http://fr.archive.ubuntu.com/ubuntu/ xenial main restricted universe multiverse" # We need an up-to-date MinGW
      sudo apt-get update
      sudo apt-get install -t xenial gcc-mingw-w64-i686 g++-mingw-w64-i686 mingw32-runtime
    else
      sudo apt-get -qy install libsdl2-dev rpm libegl1-mesa-dev libgles2-mesa-dev libxi-dev libxrandr-dev freeglut3  # freeglut probably pulls libxi-dev in
    fi
  elif [ "$TRAVIS_OS_NAME" == "osx" ]
  then
    brew update
    brew install sdl2
  fi
script: |-
  if [ "$CROSS" == "mingw64" ]
  then
    ./makecrosswin.sh
  else
    if [ "$CXX" == "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
    ./build.sh || exit 1
    if [ "$DEPLOY_DEB" == "yes" ] || [ "$DEPLOY_RPM" == "yes" ]
    then
      pushd release_build
      make package
      popd
    fi
  fi
before_deploy: |-
  if [ "$TRAVIS_OS_NAME" == "osx" ]
  then
    export DEPLOY_FILES=build/release/mupdf-macos
  elif [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$CROSS" == "mingw64" ]
  then
    export DEPLOY_FILES=build/release/mupdf-win.exe
  else
    export DEPLOY_FILES=build/release/mupdf-linux
  fi
deploy:
  provider: releases
  api_key:
    secure: o5ExTB/ZjbOApYfN5T51+hocscx+fQvs0fiejjBkxnKV7MDZv2kFX5i5AB6JFWLnHgQTCJP4dTR0AsUF9nmoyugzE/qHj2UoIDKbaPI+FZuYvzKV11qSPy9xmRvaDYIKV+13lsDODNCyyXfuGawuw4qQozu1KV7+U75rRvN30pl7xg346ZEMX8BObWXiQ3uMXTwNNcFcMIBLrQ3bcYBvrltRET3uj7Hm7tkdY4CVTqiWkPAJGEzQikiS13P8HJmAI4ed/d3XnjsJDJCl2j++FacBbpwZ7AA55PyFXcSOUSp9iS3kWR/n71uOIP9qti7z0qTFkd3J7S9zl3xgLycPBqyzEGDXmyzySZwz+ndwpBxGhfwJ4iSPHMVuMgbVVX9GfgApmB+efHMCzig+soplPMamLHKyhq2wQoNgOUbMMj+5b4CdmEEZ0yQTf7HlZ4XLYEl7GuilUZFpDJX0Xu20bq4mxb6GgqoODdaPKOvjONw0MaQ9C3oElScXSNVQxBzlQ5yDKIm9T8raw6bq9GjxUHTLld4R5BD3ZbtMZXmBn66WhrdfJafCiM5nogJUbfQha7/9yLOYF2CSBFqpts5bPJY7mqB6U9Hn5zxeThvm+uyOZxF0NfCm6/WmUx17N8k3G4vkwiH4GX66u/NuC4HSHzSPCyaWrp5+QjjCDI3rUl0=
  file: "${DEPLOY_FILES}"
  skip_cleanup: true
  on:
    condition: "$DEPLOY == yes"
    repo: pvtinflex/fbvpdf
