language: C
git:
  depth: 9999999
os:
- linux
compiler:
- clang
matrix:
  include:
  - os: osx
    compiler: clang
    env: VERS=macos DEPLOY=yes
  - os: linux
    compiler: gcc
    env: VERS=win DEPLOY=yes
  - os: linux
    compiler: gcc
    env: VERS=linux DEPLOY=yes
dist: trusty
sudo: required
branches:
  only: master
install: |-
  if [ "$VERS" == "win" ] # Cross compiling for Windows
  then
    sudo add-apt-repository "deb http://fr.archive.ubuntu.com/ubuntu/ xenial main restricted universe multiverse" # We need an up-to-date MinGW
    sudo apt-get update
    sudo apt-get -qy install libsdl2-dev rpm libegl1-mesa-dev libgles2-mesa-dev libxi-dev libxrandr-dev freeglut3
    sudo apt-get install -t xenial gcc-mingw-w64-i686 g++-mingw-w64-i686 mingw32-runtime
  elif [ "$VERS" == "linux" ]
  then
    sudo apt-get -qy install libsdl2-dev rpm libegl1-mesa-dev libgles2-mesa-dev libxi-dev libxrandr-dev freeglut3  # freeglut probably pulls libxi-dev in
  elif [ "$VERS" == "macos" ]
  then
    echo "Building macOS"
    brew install sdl2
  fi
script: |-
  if [ "$VERS" == "win" ]
  then
    ./makecrosswin.sh || exit 1
  elif [ "$VERS" == "linux" ]
  then
    if [ "$CXX" == "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
    ./makelinux.sh || exit 1
  elif [ "$VERS" == "macos" ]
  then
    if [ "$CXX" == "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
    ./makemacos.sh || exit 1
  fi
before_deploy: |-
  if [ "$VERS" == "macos" ]
  then
    export DEPLOY_BIN=fbvpdf-macos.zip
    export DEPLOY_PKG=fbvpdf.dmg
  elif [ "$VERS" == "win" ]
  then
    export DEPLOY_BIN=build/release/mupdf-win.exe
    export DEPLOY_PKG=fbvpdf.zip
  elif [ "$VERS" == "linux" ]
  then
    export DEPLOY_BIN=build/release/mupdf-linux
    export DEPLOY_PKG=fbvpdf.tar.gz
  fi
deploy:
  provider: releases
  api_key:
    secure: iu9LXPXN9stjAajI8+C9mYu0RXxNKcwKLYjXDBnOakFihHoPTz1DC1LKCuGAf1rDTA55Ytotz8oHrnTDKE/dCRaBV8Y4sYq/Fin4FRT6X5QvLGi3vUoZ7gtwo4tfeHfQ2XnhjRdmc9nym1qImNi0e4PGGcBQ/BRxgm8GB34Ux6h3JAzuBIVp2Mc2414eZ4UunUcCHG2g3x+UiQpTW+kEcjQbf4AaEyGTbcsHoanVBFF39WyWaqCnES1RwzYgev74y240hvwdvjF1RkfPdMOS2GTqJdZMNFtc4iNT79e1OiPkWTck6YF3WTHz1bdhP8jLIxVfRdhtPsiSucmdqymd+C5thyKVM28jcD4Ki9HWBSshzi+HLXiyWVIYbSP6A99Tr5UC+eAkJFayuCNyE0iFe4VyTCN30HG7i27tDcdCz52LopJi4Vcecd1JiYE2OlTnPp2qQ24MsIc1gXIKM5VPMFeEPqPcLxg4gnSe3s9i3V6/wrdMebqJgOsAg7dxTpT5jbbfq8ubs0rSe/rX0gIkicvK7q6PjNE+vcMg+Vm3RsB3lNpSRfjbwQBtZ+0oZgudVsDW3HUWgAqW6K7wgAAg2FcAi6ohVPK5WgnoHUrPI2G5Zta8zq7gNobkvET2TRw8/Po0xDJpy1UgW7tVL0V7e3xQqPu1qprJP60Z9ObGplw=
  file:
    - "${DEPLOY_BIN}"
    - "${DEPLOY_PKG}"
  skip_cleanup: true
  on:
    repo: pvtinflex/fbvpdf
